version: 2
project_name: braintrust-sdk-go

builds:
  - skip: true

release:
  github:
    owner: braintrustdata
    name: braintrust-sdk-go
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - 'merge pull request'
